# Generated by Django 3.0.5 on 2020-04-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_auto_20200427_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='sort_order',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='sort_order',
            field=models.IntegerField(unique=True),
        ),
    ]
