# Generated by Django 3.0.5 on 2020-04-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_auto_20200427_1230'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('show', 'sort_order'), name='unique sort_order'),
        ),
        migrations.AlterModelTable(
            name='image',
            table='sort_order',
        ),
    ]
