# Generated by Django 3.0.1 on 2019-12-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='image_filename',
        ),
        migrations.AddField(
            model_name='show',
            name='department',
            field=models.CharField(default='LIGHTING DESIGN', max_length=64),
        ),
    ]
