# Generated by Django 3.0.5 on 2020-04-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
