# Generated by Django 3.0.1 on 2019-12-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_show_image_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='show',
            name='cover_image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
